### PR TITLE
Restore .gitignore and add git submodule 

### PR DESCRIPTION
**Pull request by danizen**
Since @reavon overwrote my changes to .gitignore in merge, and added a new dependency on ansible-role-aws without adding a git submodule, I have to be forceful, and merge again.   Ruby is not ready, but ansible-role-aws is added here as a submodule.

### CODE REVIEW

**Comment by reavon** [comment]
eeeek sorry about that

**Comment by danizen** [comment]
Its ok - but you seriously need to ask if the submodules don't work for you.   Just move the current things out of the way to a parallel data structure, and run, I think, git submodule init, and it will populate the sub-directories again.   Let me know if it doesn't work that way.

**Comment by reavon** [comment]
I don't even use them yet since the "submodules" for me right now they are in `ansible/roles/`. Once you have a role for me to use, I will move them out. I forgot all about you using submodules for the roles.

**Comment by danizen** [comment]
I have committed 3 new roles, none of which are used in the Base template, but all of which are in the Ruby template.   I just checked it out at home, and after checking it out, I had to run the following to get your  roles to populate:

```
dan@petrock:~/code$ git clone git@github.com:NLM-OCCS/occs-packer.git
Cloning into 'occs-packer'...
remote: Counting objects: 225, done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 225 (delta 39), reused 0 (delta 0), pack-reused 109
Receiving objects: 100% (225/225), 60.29 KiB | 0 bytes/s, done.
Resolving deltas: 100% (69/69), done.
Checking connectivity... done.
dan@petrock:~/code$ cd occs-packer
dan@petrock:~/code/occs-packer$ ls ansible/roles/ansible-directories
dan@petrock:~/code/occs-packer$ git submodule init
...
dan@petrock:~/code/occs-packer$ git submodule update
...
dan@petrock:~/code/occs-packer$ ls ansible/roles/ansible-directories
defaults  handlers    meta         tasks      tests
files     LICENSE.md  README.adoc  templates  vars
dan@petrock:~/code/occs-packer$ 
```

**Pull request merged**
